public with sharing class Exeptionrevision {
    // Exeption types:

// DML - Query - Math - Null- LIst_ generric- limit


// try - catch block 
// Can we do independent try block ? NO 
// Can we multiple cathces? YES 
   // Generic exeption must be at the end ( Exeption x)  


//====> How to handle, what we do after catch?
// - display user friendly message 
//- fail silently ( do nothing)
// -send e mail to user or admin 
// -log errors in error objects
// -retry ( very rare)
}